name: Deploy to Production

on:
  push:
    branches:
      - Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PROD_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
          cd ${{ secrets.PROD_PATH }}
          git pull origin prod
          npm install --production
          pm2 restart ncntaia
        EOF

